SAMPLES = [
	"b_malayi.PRJNA10729.WS282",
	"c_brenneri.PRJNA20035.WS282",
	"c_briggsae.PRJNA10731.WS282",
	"c_elegans.PRJNA13758.WS282",
	"c_japonica.PRJNA12591.WS282",
	"c_remanei.PRJNA53967.WS282",
	"o_volvulus.PRJEB513.WS282",
	"p_pacificus.PRJNA12644.WS282",
	"s_ratti.PRJEB125.WS282",
	"t_muris.PRJEB126.WS282"
]

# haman outputs as .gff not .gff3 like it says on github
EXTS = [".fa", ".gff"]

rule all:
	input:
		expand("genome_builds/{sample}.1pct{ext}", sample=SAMPLES, ext=EXTS)

rule download_genomes:
	output:
		"ref/c_elegans.PRJNA13758.WS282.annotations.gff3.gz",
		"ref/c_elegans.PRJNA13758.WS282.genomic.fa.gz",
		"ref/c_brenneri.PRJNA20035.WS282.annotations.gff3.gz",
		"ref/c_brenneri.PRJNA20035.WS282.genomic.fa.gz",
		"ref/c_briggsae.PRJNA10731.WS282.annotations.gff3.gz",
		"ref/c_briggsae.PRJNA10731.WS282.genomic.fa.gz",
		"ref/c_japonica.PRJNA12591.WS282.annotations.gff3.gz",
		"ref/c_japonica.PRJNA12591.WS282.genomic.fa.gz",
		"ref/c_remanei.PRJNA53967.WS282.annotations.gff3.gz",
		"ref/c_remanei.PRJNA53967.WS282.genomic.fa.gz",
		"ref/b_malayi.PRJNA10729.WS282.annotations.gff3.gz",
		"ref/b_malayi.PRJNA10729.WS282.genomic.fa.gz",
		"ref/o_volvulus.PRJEB513.WS282.annotations.gff3.gz",
		"ref/o_volvulus.PRJEB513.WS282.genomic.fa.gz",
		"ref/p_pacificus.PRJNA12644.WS282.annotations.gff3.gz",
		"ref/p_pacificus.PRJNA12644.WS282.genomic.fa.gz",
		"ref/s_ratti.PRJEB125.WS282.annotations.gff3.gz",
		"ref/s_ratti.PRJEB125.WS282.genomic.fa.gz",
		"ref/t_muris.PRJEB126.WS282.annotations.gff3.gz",
		"ref/t_muris.PRJEB126.WS282.genomic.fa.gz"
	shell:
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS282.annotations.gff3.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS282.genomic.fa.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"c_brenneri/PRJNA20035/c_brenneri.PRJNA20035.WS282.annotations.gff3.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"c_brenneri/PRJNA20035/c_brenneri.PRJNA20035.WS282.genomic.fa.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"c_briggsae/PRJNA10731/c_briggsae.PRJNA10731.WS282.annotations.gff3.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"c_briggsae/PRJNA10731/c_briggsae.PRJNA10731.WS282.genomic.fa.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"c_japonica/PRJNA12591/c_japonica.PRJNA12591.WS282.annotations.gff3.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"c_japonica/PRJNA12591/c_japonica.PRJNA12591.WS282.genomic.fa.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"c_remanei/PRJNA53967/c_remanei.PRJNA53967.WS282.annotations.gff3.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"c_remanei/PRJNA53967/c_remanei.PRJNA53967.WS282.genomic.fa.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"b_malayi/PRJNA10729/b_malayi.PRJNA10729.WS282.annotations.gff3.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"b_malayi/PRJNA10729/b_malayi.PRJNA10729.WS282.genomic.fa.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"o_volvulus/PRJEB513/o_volvulus.PRJEB513.WS282.annotations.gff3.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"o_volvulus/PRJEB513/o_volvulus.PRJEB513.WS282.genomic.fa.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"p_pacificus/PRJNA12644/"
		"p_pacificus.PRJNA12644.WS282.annotations.gff3.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"p_pacificus/PRJNA12644/p_pacificus.PRJNA12644.WS282.genomic.fa.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"s_ratti/PRJEB125/s_ratti.PRJEB125.WS282.annotations.gff3.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"s_ratti/PRJEB125/s_ratti.PRJEB125.WS282.genomic.fa.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"t_muris/PRJEB126/t_muris.PRJEB126.WS282.annotations.gff3.gz"
		" -P ref/\n"
		"wget https://downloads.wormbase.org/releases/WS282/species/"
		"t_muris/PRJEB126/t_muris.PRJEB126.WS282.genomic.fa.gz"
		" -P ref/\n"

rule gff_strip:
	input:
		"ref/{sample}.annotations.gff3.gz"
	output:
		"stripped_gffs/{sample}.stripped.gff3"
	shell:
		"gunzip -c {input} | grep -E 'WormBase|RNASeq' > {output}"

rule build_genome:
	input:
		fasta="ref/{sample}.genomic.fa.gz",
		gff="stripped_gffs/{sample}.stripped.gff3"
	output:
		multiext("genome_builds/{sample}.1pct", ".fa", ".gff")
	shell:
		"haman {input.fasta} {input.gff} pct genome_builds/{wildcards.sample}.1pct --pct 1"

rule build_genes:
	input:
		fasta=expand("genome_builds/{sample}.1pct.fa", sample=SAMPLES),
		gff=expand("genome_builds/{sample}.1pct.gff", sample=SAMPLES)
	output:
		"minigene/"
	shell:
		"haman {input.fasta} {input.gff} pcg minigene"


























