rule all:
	input:
		"blastdbs/c_briggsae.PRJNA10731.WS284.genomic.done"

# helped fix error: 
# https://stackoverflow.com/questions/59288002/missingoutputexception-and-laten
# cy-wait-error-with-snakemake
# files are still made without touch(), but latency wait error is thrown
# i think touch() makes the file so snakemake can find them? not really sure
# creates a dummy .done file, idk how to remove it without errors

rule makeblastdb:
	input:
		"input/ref/c_briggsae.PRJNA10731.WS284.genomic.fa"
	output:
		touch("blastdbs/c_briggsae.PRJNA10731.WS284.genomic.done")
	shell:
		"makeblastdb -in {input} -dbtype nucl -out blastdbs/c_briggsae.PRJNA10731.WS284.genomic"
