# goal is to find the proteins in the APC dataset
# make own translator-glue CDS's together from apc_test
# do a blastp protein to protein
# download all the protein sequences
# blast the APC proteomes together
'''
GENOMES = ["c_briggsae.PRJNA10731.WS285", "c_japonica.PRJNA12591.WS285"]
EXTS = [".ndb", ".nhr", ".nin", ".njs", ".not", ".nsq", ".ntf", ".nto"]
SAMPLES = ["10010", "10019", "10087", "10164", "10192"]

rule all:
	input:
		#expand("blastdbs/{genome}.blastdb.dummy", genome=GENOMES)
		expand("output/{genome}.{sample}.blastout.tsv", genome=GENOMES, sample=SAMPLES)

rule makeblastdb:
	input:
		"input/ref/{genome}.genomic.fa"
	output:
		#touch("blastdbs/{genome}.blastdb.dummy")
		multiext("blastdbs/{genome}.blastdb", ".ndb", ".nhr", ".nin", ".njs", ".not", ".nsq", ".ntf", ".nto")
	shell:
		"""
		makeblastdb -in {input} -dbtype nucl -out blastdbs/{wildcards.genome}.blastdb
		touch {output}
		"""

rule run_blastn:
	input:
		expand("blastdbs/{genome}.blastdb{ext}", genome=GENOMES, ext=EXTS),
		query = "input/apc_test/ch.{sample}.fa"
	output:
		"output/{genome}.{sample}.blastout.tsv"
	shell:
		"blastn -db blastdbs/{wildcards.genome}.blastdb -query {input.query} "
		"-evalue 1e-3 -outfmt '7 std stitle' > {output}"
'''
'''
rule get_genomes:
	output:
		"ref/c_elegans.PRJNA13758.WS285.genomic.fa.gz",
		"ref/c_brenneri.PRJNA20035.WS285.genomic.fa.gz",
		"ref/c_briggsae.PRJNA10731.WS285.genomic.fa.gz",
		"ref/c_japonica.PRJNA12591.WS285.genomic.fa.gz",
		"ref/c_remanei.PRJNA577507.WS285.genomic.fa.gz",
		"ref/b_malayi.PRJNA10729.WS285.genomic.fa.gz",
		"ref/o_volvulus.PRJEB513.WS285.genomic.fa.gz",
		"ref/p_pacificus.PRJNA12644.WS285.genomic.fa.gz",
		"ref/s_ratti.PRJEB125.WS285.genomic.fa.gz",
		"ref/t_muris.PRJEB126.WS285.genomic.fa.gz"
	shell:
		"wget ftp://ftp.wormbase.org/pub/wormbase/releases/WS285/species/"
		"c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS285.genomic.fa.gz"
		" -P ref/\n"
		"wget ftp://ftp.wormbase.org/pub/wormbase/releases/WS285/species/"
		"c_brenneri/PRJNA20035/c_brenneri.PRJNA20035.WS285.genomic.fa.gz"
		" -P ref/\n"
		"wget ftp://ftp.wormbase.org/pub/wormbase/releases/WS285/species/"
		"c_briggsae/PRJNA10731/c_briggsae.PRJNA10731.WS285.genomic.fa.gz"
		" -P ref/\n"
		"wget ftp://ftp.wormbase.org/pub/wormbase/releases/WS285/species/"
		"c_japonica/PRJNA12591/c_japonica.PRJNA12591.WS285.genomic.fa.gz"
		" -P ref/\n"
		"wget ftp://ftp.wormbase.org/pub/wormbase/releases/WS285/species/"
		"c_remanei/PRJNA577507/c_remanei.PRJNA577507.WS285.genomic.fa.gz"
		" -P ref/\n"
		"wget ftp://ftp.wormbase.org/pub/wormbase/releases/WS285/species/"
		"b_malayi/PRJNA10729/b_malayi.PRJNA10729.WS285.genomic.fa.gz"
		" -P ref/\n"
		"wget ftp://ftp.wormbase.org/pub/wormbase/releases/WS285/species/"
		"o_volvulus/PRJEB513/o_volvulus.PRJEB513.WS285.genomic.fa.gz"
		" -P ref/\n"
		"wget ftp://ftp.wormbase.org/pub/wormbase/releases/WS285/species/"
		"p_pacificus/PRJNA12644/p_pacificus.PRJNA12644.WS285.genomic.fa.gz"
		" -P ref/\n"
		"wget ftp://ftp.wormbase.org/pub/wormbase/releases/WS285/species/"
		"s_ratti/PRJEB125/s_ratti.PRJEB125.WS285.genomic.fa.gz"
		" -P ref/\n"
		"wget ftp://ftp.wormbase.org/pub/wormbase/releases/WS285/species/"
		"t_muris/PRJEB126/t_muris.PRJEB126.WS285.genomic.fa.gz"
		" -P ref/"
'''	
SPECIES=[
	"c_elegans.PRJNA13758",
	"c_brenneri.PRJNA20035",
	"c_briggsae.PRJNA10731",
	"c_japonica.PRJNA12591",
	"c_remanei.PRJNA577507",
	"b_malayi.PRJNA10729",
	"o_volvulus.PRJEB513",
	"p_pacificus.PRJNA12644",
	"s_ratti.PRJEB125",
	"t_muris.PRJEB126"
]		

rule all:
	input:
		expand("ref/{sample}.WS285.genomic.fa", sample=SPECIES)

rule unzip_genomes:
	input:
		"ref/{sample}.WS285.genomic.fa.gz"
	output:
		"ref/{sample}.WS285.genomic.fa"
	shell:
		"gzip -dk {input}"





















