---
IDs: [4884, 7395]
# these parameters are set to the geniso defaults
min_intron: 35
min_exon: 25
max_splice: 3
flank: 99
iso_limit: 20

dpwm_path: 'data/donor.pwm'
apwm_path: 'data/acceptor.pwm'
emm_path: 'data/exon.mm'
imm_path: 'data/intron.mm'
elen_path: 'data/exon.len'
ilen_path: 'data/intron.len'
