---
root.dir: /home/carl/Code/isoforms/apc/
---

```{r}
#apc_dir <- "/home/carl/Code/splicing/Ranalysis/sub/"
# full data
apc_dir <- "/home/carl/Code/isoforms/apc/"
g_files <- list.files(apc_dir, pattern = ".gff3")
g_paths <- sapply(seq_along(g_files), function(x) {
  paste(apc_dir, g_files[x], sep = "")
})
rm(g_files)
```

```{r}
library(dplyr)
library(tidyr)
```

```{r}
gffs_df <- lapply(g_paths, function(x) {
  read.table(x, header = FALSE, sep = "\t")
}) %>%
  do.call('rbind',.) 

colnames(gffs_df) <- c("seqid", "source", "type", "start", "end", "score", 
                       "strand", "phase", "attributes")
```

```{r}
tmp1 <- gffs_df
tmp2 <- tmp1 %>%
  select(seqid, start, end) %>% # need ids to create unique introns
  unite(., "start_end", sep = ",")

gdata <- mutate(tmp1, tmp2)
rm(tmp1, tmp2)
```

Use case_when() in mutate() to add a new column to a df based on a comparison between other columns in the df.

```{r}
gdata <- gdata %>% 
  mutate(wb_int = case_when(
    source == "WormBase" & type == "intron" ~ TRUE,
                            TRUE ~ FALSE))
```

Create a vector with all introns that are wormbase introns. Which gene each intron belongs to is also included.

```{r}
# subset using logicals T/F
wb_ints <- gdata$start_end[gdata$wb_int]
```

```{r}
# labels all the top scoring isoforms
gdata <- gdata %>% 
  mutate(int_score = case_when(
    start_end %in% wb_ints & source == "RNASeq_splice" ~ TRUE,
    TRUE ~ FALSE
  ))
```

Very useful: https://dplyr.tidyverse.org/articles/rowwise.html Can do operations on a per row basis install of all columns

```{r}
# don't forget comma; ,] means all columns
# df[rows, columns]
# automatically gets the true columns
top_ints <- gdata[gdata$int_score,] 

get_len <- function(beg, end) {
  return(end - beg + 1)
}

top_ints <- top_ints %>% 
  rowwise() %>% 
  mutate(length = get_len(start, end))
```


```{r}
library(ggplot2)
# all canonical introns, score not considered 
p <- ggplot(data = top_ints, aes(x = length)) +
  geom_histogram(bins = length(unique(top_ints$length))) +
  labs(title = "canonical introns",
       x = "intron length",
       y = "counts (eg 103 introns of length45 ")

p
```
Make histogram with all introns that appear in the APC dataset
```{r}
all_ints <- gdata[gdata$source == "RNASeq_splice",]

all_ints <- all_ints %>% 
  rowwise() %>% 
  mutate(length = get_len(start, end))

uniq_lens <- data.frame(unique(all_ints$length))
colnames(uniq_lens) <- c('length')

tx_counter <- function(x, df) {
  tmp <- df[df$length == x,]
  return(sum(as.numeric(tmp$score)))
}

# !! calls global variable, instead of piped df values
tx_counts <- uniq_lens %>% 
  rowwise() %>% 
  mutate(counts = tx_counter(length, !!all_ints))

```

```{r}
p_int <- ggplot(data = tx_counts, aes(x = length, y = counts)) +
  geom_bar(stat = "identity") +
  labs(title = "all introns",
       x = "intron length",
       y = "transcript counts (score)") +
  ylim(0, max(tx_counts$counts) + 10) +
  xlim(0, max(tx_counts$length) + 10)
p_int
```




